In [1]:
import torch
import numpy as np
from overcooked_env import OvercookedEnv
from rl_utils import vectorize_world_state, flip_array
from settings import AI_AGENTS, HUMAN_AGENTS

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
final_HUMAN_AGENTS = {k:v for k,v in HUMAN_AGENTS.items() if k == '1'}
AI_AGENTS_TO_INITIALIZE = {}
for idx in range(1, 2+1):
    idx = str(idx)
    AI_AGENTS_TO_INITIALIZE[idx] = AI_AGENTS[idx]

env = OvercookedEnv(
                human_agents=final_HUMAN_AGENTS,
                ai_agents=AI_AGENTS_TO_INITIALIZE)

Removing agent current location from valid_cells, valid_item_cells list
Valid cell is already updated


In [4]:
actions = {agent: (0,1) for agent in env.world_state['agents']}
print (env.world_state['agents'][0].location)
print (vectorize_world_state(env.world_state)[0,0])

env.step(actions)
print (env.world_state['agents'][0].location)
print (vectorize_world_state(env.world_state)[0,0])

(4, 1)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] /n
@map_env - step()
{<human_agent.HumanAgent object at 0x7f625dc047f0>: (0, 1), <overcooked_agent.OvercookedAgent object at 0x7f625dc04860>: (0, 1), <overcooked_agent.OvercookedAgent object at 0x7f625dc04908>: (0, 1)}
@map_env - update_moves()
{<human_agent.HumanAgent object at 0x7f625dc047f0>: (0, 1), <overcooked_agent.OvercookedAgent object at 0x7f625dc04860>: (0, 1), <overcooked_agent.OvercookedAgent object at 0x7f625dc04908>: (0, 1)}
(0, 1)
map_env@update_moves - Movement found
(0, 1)
map_env@update_moves - Movement found
(0, 1)
map_env@update_moves - Movement found
@map_env - Starting moves (if any)
[

In [11]:
from rl_base_agent import Base_Agent, ConvMLPNetwork 

In [12]:
sample_world_state = vectorize_world_state(env.world_state)
action_space = 15
input_space = sample_world_state.shape[1]

params = {'NUM_HIDDEN_LAYERS':3,
          'SIZE_HIDDEN_LAYERS':64,
          'NUM_FILTERS':25,
          'NUM_CONV_LAYERS':3,
         'OBS_STATE_SHAPE':(sample_world_state.shape[-1],sample_world_state.shape[-2])}

ppo = ConvMLPNetwork(input_size = input_space, output_size = action_space, params = params)

In [13]:
ppo = ppo.double()

In [14]:
tensored_ = torch.from_numpy(sample_world_state)

In [15]:
print (13*9*25)
print (25*11*15)

2925
4125


In [16]:
ppo(tensored_)

torch.Size([1, 25, 11, 15])
torch.Size([1, 25, 9, 13])


/home/sidney/aiap/ToM-gameplaying-POMDP/overcooked_server/rl_base_agent.py:371: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x = F.softmax(linear_final(x))


tensor([[0.0721, 0.0740, 0.0676, 0.0606, 0.0645, 0.0697, 0.0719, 0.0614, 0.0642,
         0.0659, 0.0687, 0.0704, 0.0653, 0.0586, 0.0651]],
       dtype=torch.float64, grad_fn=<SoftmaxBackward>)